Vermelho=#FF0000
Verde=#00FF00
Azul=#0000FF
Amarelo=#FFFF00
Laranja=#FFA500
Roxo=#800080
Rosa=#FFC0CB
Marrom=#8B4513
Cinza=#808080
Preto=#000000
Branco=#FFFFFF
Turquesa=#40E0D0
Vinho=#800000
Dourado=#FFD700
Prata=#C0C0C0
Bege=#F5F5DC
Oliva=#808000
Lima=#BFFF00
Ciano=#00FFFF
Magenta=#FF00FF
Salmão=#FA8072
Coral=#FF7F50
Lavanda=#E6E6FA
Indigo=#4B0082
Chocolate=#D2691E
Aqua=#00CED1
AzulMarinho=#000080
Esmeralda=#50C878
Grafite=#2F4F4F
Menta=#98FF98
Tijolo=#B22222
Bronze=#CD7F32